### ISSUE TITLE
Errors with Preview when building static site with Nuxtjs

### ISSUE THREAD

**Issue by bbusch19** [prismicio/prismic-javascript#112]
### Issue
When using the `nuxt generate` command, I get the following error from my `Preview.vue` file:
```javascript
 ERROR  Only absolute URLs are supported                                                                                                           15:46:07

  at getNodeRequestOptions (node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1284:9)
  at node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1370:19
  at new Promise (<anonymous>)
  at Object.fetch (node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1367:9)
  at Object.fetch (node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
  at node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15320
  at t.request (node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15646)
  at t.request (node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:18526)
  at node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:4190
  at new Promise (<anonymous>)
  at t.previewSession (node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:4151)
  at asyncData (1683ba156641ce86efa8.js:1:299)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This is the code I am using to generate the Preview:
```javascript
<script>
import Prismic from 'prismic-javascript'
import LinkResolver from '~/plugins/link-resolver.js'
import PrismicConfig from '~/prismic.config.js'

export default {
  name: 'Preview',
  async asyncData({ query, redirect }) {
    const previewToken = query.token
    const api = await Prismic.getApi(PrismicConfig.apiEndpoint)
    const url = await api.previewSession(previewToken, LinkResolver, '/')
    redirect(url)
  }
}
</script>
```
### Expected Behavior
I should be able to access the Preview functionality even with static site generators. This is possible with other platforms like Gatsby.

**Comment by Duaner** [comment]
Hello  @bbusch19 

This is now possible with the prismic-module for nuxt. 
You can see it here. 

https://github.com/nuxt-community/prismic-module

If there is any issue with this, can you report issues on this project, please? 

Closing this. 
Thanks a lot.
