### ISSUE TITLE
TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by tylermcrobert** [prismicio/prismic-javascript#120]
When trying to use previews in nextJS i'm getting the following error. I have another NextJS project that's using Prismic where i'm using the same preview code and i'm not getting the same error.

```
TypeError: Only absolute URLs are supported
--
06:44:58 PM | at getNodeRequestOptions (/zeit/14838dcb/node_modules/prismic-javascript/node_modules/node-fetch/lib/index.js:1284:9)
06:44:58 PM | at /zeit/14838dcb/node_modules/prismic-javascript/node_modules/node-fetch/lib/index.js:1370:19
06:44:58 PM | at new Promise (<anonymous>)
06:44:58 PM | at Object.fetch (/zeit/14838dcb/node_modules/prismic-javascript/node_modules/node-fetch/lib/index.js:1367:9)
06:44:58 PM | at Object.fetch (/zeit/14838dcb/node_modules/prismic-javascript/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
06:44:58 PM | at /zeit/14838dcb/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15397
06:44:58 PM | at t.request (/zeit/14838dcb/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15723)
06:44:58 PM | at t.request (/zeit/14838dcb/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:18603)
06:44:58 PM | at /zeit/14838dcb/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:4155
06:44:58 PM | at new Promise (<anonymous>)
```

**Comment by Heyrows** [comment]
Hi Tyler,

Could you give us some details about the context (api calls, part of the code, ...) to help us understand or reproduce your issue.

**Comment by Duaner** [comment]
Closing this one since no activity from more than 3 months
