### ISSUE TITLE
Errors with v6 Fetch in Svelte

### ISSUE THREAD

**Issue by samlfair** [prismicio/prismic-javascript#179]
I'm getting this error with the v6 client in SvelteKit:
```
TypeError: this.fetchFn is not a function
    at Client.fetch (/Users/samlittlefair/Documents/reproduction/2021/svelte-docs-1/node_modules/@prismicio/client/dist/index.cjs:501:28)
    at Client.getRepository (/Users/samlittlefair/Documents/reproduction/2021/svelte-docs-1/node_modules/@prismicio/client/dist/index.cjs:327:23)
    at Client.getCachedRepository (/Users/samlittlefair/Documents/reproduction/2021/svelte-docs-1/node_modules/@prismicio/client/dist/index.cjs:436:35)
    at Client.getResolvedRefString (/Users/samlittlefair/Documents/reproduction/2021/svelte-docs-1/node_modules/@prismicio/client/dist/index.cjs:489:39)
    at Client.buildQueryURL (/Users/samlittlefair/Documents/reproduction/2021/svelte-docs-1/node_modules/@prismicio/client/dist/index.cjs:368:24)
    at Client.get (/Users/samlittlefair/Documents/reproduction/2021/svelte-docs-1/node_modules/@prismicio/client/dist/index.cjs:269:28)
    at Client.getAll (/Users/samlittlefair/Documents/reproduction/2021/svelte-docs-1/node_modules/@prismicio/client/dist/index.cjs:283:31)
    at load (index.svelte:7:39)
    at load_node (file:///Users/samlittlefair/Documents/reproduction/2021/svelte-docs-1/node_modules/@sveltejs/kit/dist/ssr.js:818:30)
    at respond$1 (file:///Users/samlittlefair/Documents/reproduction/2021/svelte-docs-1/node_modules/@sveltejs/kit/dist/ssr.js:1039:21)
```

This could be a bug in my code, but I know Priyanka was having some trouble as well.

Relevant files: 

https://github.com/samlfair/svelte-docs-tester-01/blob/master/src/routes/index.svelte

https://github.com/samlfair/svelte-docs-tester-01/blob/master/src/lib/client.js

Client looks like this:
```js
// /src/lib/client.js

import { createClient, getEndpoint } from '@prismicio/client'

const repoName = `your-repo-name` // Fill in your repository name
const endpoint = getEndpoint(repoName)

export default Client = (session, fetch) => {
  const { cookie } = session
  const req = {
    headers: {
      cookie,
    },
  }
  const client = createClient(endpoint, { fetch, req })
  return client
}
```

Index route looks like this:
```svelte
<!-- /src/routes/index.js -->

<script context="module">
  import Client from '$lib/client.js';
  
  export async function load({ fetch, session })  {
    const client = Client(fetch, session)
    const allDocs = await client.getAll()
    return allDocs
  }
</script>

<script>
  export let allDocs;
</script>

<h1>Welcome to SvelteKit</h1>
<pre>{JSON.stringify(allDocs,null,2)}</pre>
```

**Comment by lihbr** [comment]
![image](https://user-images.githubusercontent.com/25330882/122935883-fed37180-d370-11eb-9728-55b048b6bc2b.png)
Can it be because you swap fetch & session when passing them down to the client function?

**Comment by lihbr** [comment]
Apparently, that was that. Feel free to reopen if needed ☺️
