### ISSUE TITLE
Error /preview handler on Next.js static export

### ISSUE THREAD

**Issue by imthenapo** [prismicio/prismic-javascript#70]
Following stack trace emitted...
TypeError: **Only absolute URLs are supported**
    at getNodeRequestOptions (C:\Users\Napo\Documents\Github\yafo\node_modules\cross-fetch\node_modules\node-fetch\lib\index.js:1284:9)
    at C:\Users\Napo\Documents\Github\yafo\node_modules\cross-fetch\node_modules\node-fetch\lib\index.js:1370:19
    at new Promise (<anonymous>)
    at Object.fetch (C:\Users\Napo\Documents\Github\yafo\node_modules\cross-fetch\node_modules\node-fetch\lib\index.js:1367:9)
    at Object.fetch (C:\Users\Napo\Documents\Github\yafo\node_modules\cross-fetch\dist\node-ponyfill.js:10:20)
    at C:\Users\Napo\Documents\Github\yafo\node_modules\prismic-javascript\dist\prismic-javascript.min.js:1:14816
    at u (C:\Users\Napo\Documents\Github\yafo\node_modules\prismic-javascript\dist\prismic-javascript.min.js:1:15142)
    at t.request (C:\Users\Napo\Documents\Github\yafo\node_modules\prismic-javascript\dist\prismic-javascript.min.js:1:15319)
    at C:\Users\Napo\Documents\Github\yafo\node_modules\prismic-javascript\dist\prismic-javascript.min.js:1:18238
    at new Promise (<anonymous>)

**Comment by arnaudlewis** [comment]
Yes indeed, with the static export, and if you rely on our next.js example, the query token is empty so the kit is trying to fetch an undefined URL. So It's handled by Prismic.js and works perfectly with the static export.
I fixed it here : https://github.com/prismicio/prismic-nextjs-sample
