### ISSUE TITLE
fetch is not defined

### ISSUE THREAD

**Issue by krabbypattified** [prismicio/prismic-javascript#79]
Opening this issue on behalf of a client.

```js
import Prismic from'prismic-javascript';

…

getComponents = ()=>{

let { cookies } = this.props;

Prismic.api(apiEndpoint).then(api => {

api.query(Prismic.Predicates.at('document.type', 'landingpage')).then(response => {

if(response) {

if(Cookies){

let res = response.results[0].data;

console.log(res);

}

}

});

}
```
On localhost everything works fine. But I get the is error on Heroku. 

```
UnhandledPromiseRejectionWarning: ReferenceError: fetch is not defined

(node:22) UnhandledPromiseRejectionWarning: ReferenceError: fetch is not defined
2019-01-16T14:36:21.424550+00:00 app[web.1]: at /app/build/static/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15368
2019-01-16T14:36:21.424553+00:00 app[web.1]: at r (/app/build/static/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15723)
2019-01-16T14:36:21.424554+00:00 app[web.1]: at e.request (/app/build/static/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15909)
2019-01-16T14:36:21.424556+00:00 app[web.1]: at e.request (/app/build/static/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:18769)
2019-01-16T14:36:21.424557+00:00 app[web.1]: at /app/build/static/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:19012
2019-01-16T14:36:21.424558+00:00 app[web.1]: at e.get (/app/build/static/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:18207)
2019-01-16T14:36:21.424559+00:00 app[web.1]: at /app/build/static/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:18984
2019-01-16T14:36:21.424561+00:00 app[web.1]: at /app/build/static/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:19089
2019-01-16T14:36:21.424563+00:00 app[web.1]: at new Promise (<anonymous>)
2019-01-16T14:36:21.424565+00:00 app[web.1]: at e.cachedRequest (/app/build/static/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:18918)
2019-01-16T14:36:21.424566+00:00 app[web.1]: at e.get (/app/build/static/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:4960)
2019-01-16T14:36:21.424567+00:00 app[web.1]: at Function.e.getApi (/app/build/static/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:20826)
2019-01-16T14:36:21.424569+00:00 app[web.1]: at t (/app/build/static/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:20983)
2019-01-16T14:36:21.424570+00:00 app[web.1]: at Object.e.api (/app/build/static/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:21244)
2019-01-16T14:36:21.424571+00:00 app[web.1]: at t.n.getComponents (/app/build/static/js/components/Topbar/Topbar.js:109:13)
2019-01-16T14:36:21.424573+00:00 app[web.1]: at t.value (/app/build/static/js/components/Topbar/Topbar.js:88:10)
2019-01-16T14:36:21.424574+00:00 app[web.1]: at /app/build/static/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:27:128
2019-01-16T14:36:21.424576+00:00 app[web.1]: at m (/app/build/static/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:28:411)
2019-01-16T14:36:21.424577+00:00 app[web.1]: at e.render (/app/build/static/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:33:16)
2019-01-16T14:36:21.424578+00:00 app[web.1]: at e.read (/app/build/static/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:32:201)
2019-01-16T14:36:21.424580+00:00 app[web.1]: at Object.renderToString (/app/build/static/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:41:1)
2019-01-16T14:36:21.424582+00:00 app[web.1]: at L (/app/build/static/js/app.js:103:31)
2019-01-16T14:36:21.424584+00:00 app[web.1]: at Object.exports.render (/app/server/renderer.js:95:26)
2019-01-16T14:36:21.424585+00:00 app[web.1]: at dataLoader.loadData.then.preloadedState (/app/server/index.js:203:29)
2019-01-16T14:36:21.424587+00:00 app[web.1]: at <anonymous>
2019-01-16T14:36:21.424588+00:00 app[web.1]: at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2019-01-16T14:36:21.424782+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by vorcigernix** [comment]
Well, I'd expect better response time from Prismic.

**Comment by hypervillain** [comment]
Hey 👋

The problem here is that most probably, you're responsible for providing a `fetch` instance, which could differ depending on your existing app, environment or personal taste.

Consider requiring something like [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) at the top of your App
