### ISSUE TITLE
api.previewSession fetch issue

### ISSUE THREAD

**Issue by duvillierA** [prismicio/prismic-javascript#89]
Hi,

Stack:
- Node@10.15.2
- Next.js@8.1
- expressJs@4.16

### With `isomorphic-unfetch` 

An error occurs using api.previewSession
```js
//token = https://noname.prismic.io/previews/...?websitePreviewId=...
const url = await api.previewSession(token, PrismicLinkResolver, '/') // Line 81
```

the error stack

```js
message=url.replace is not a function, stack=TypeError: url.replace is not a function
    at module.exports.global.fetch (/Users/noname/Documents/project/node_modules/isomorphic-unfetch/index.js:3:36)
    at /Users/noname/Documents/project/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15400
    at u (/Users/noname/Documents/project/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15726)
    at t.request (/Users/noname/Documents/project/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15903)
    at t.request (/Users/noname/Documents/project/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:18781)
    at /Users/noname/Documents/project/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:4287
    at new Promise (<anonymous>)
    at t.previewSession (/Users/noname/Documents/project/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:4248)
    at Object.previewSession [as preview] (/Users/noname/Documents/project/lib/service/cms.js:81:29)
```

### Without `isomorphic-unfetch` 
An error occurs using api.previewSession
```js
//token = https://noname.prismic.io/previews/...?websitePreviewId=...
const url = await api.previewSession(token, PrismicLinkResolver, '/') // Line 81
```

The error stack 

```js
message=Only absolute URLs are supported, stack=TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/noname/Documents/project/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1284:9)
    at /Users/noname/Documents/project/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1370:19
    at new Promise (<anonymous>)
    at Object.fetch (/Users/noname/Documents/project/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1367:9)
    at Object.fetch (/Users/noname/Documents/project/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
    at /Users/noname/Documents/project/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15400
    at u (/Users/noname/Documents/project/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15726)
    at t.request (/Users/noname/Documents/project/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:15903)
    at t.request (/Users/noname/Documents/project/node_modules/prismicjavascript/dist/prismic-javascript.min.js:1:18781)
    at /Users/noname/Documents/project/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:4287
    at new Promise (<anonymous>)
    at t.previewSession (/Users/noname/Documents/project/node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:4248)
    at Object.previewSession [as preview] (/Users/noname/Documents/project/lib/service/cms.js:81:29)
```

**Comment by duvillierA** [comment]
My mistake, my bad.

**Comment by tylermcrobert** [comment]
@duvillierA Will you provide us with what you did wrong so it'll help others stumbling upon this?
